### ISSUE TITLE
blurry image error on featured image box working under layers theme

### ISSUE THREAD

**Issue by sinopsis57** [karacas/imgLiquid#45]
we could not find out why this changes original image size to odd sizes and make it blurry. here are the links you can check it:

homepage featured image (blurry):
http://vettimes.makemedia-test.com/

same image on the post with original size:
http://vettimes.makemedia-test.com/news/success-for-cattitude-feline-focused-cpd-days/

original image size is 800px × 400px, but when we make the image featured the size becomes 246px 123px which looks randomly picked. we tried to to find the function how it picks that size but we couldnt. 

does anyone can help please?

**Comment by karacas** [comment]
Mhhh, In fact the source of the image is:

http://vettimes.makemedia-test.com/wp-content/uploads/2015/08/cattitude-team-and-bertha-246x123.jpg

the which is too small (246px x 123px).

In your source:
`<a class="box-image imgLiquidFill imgLiquid" href="http://vettimes.makemedia-test.com/news/success-for-cattitude-feline-focused-cpd-days/"><img width="246" height="123" src="http://vettimes.makemedia-test.com/wp-content/uploads/2015/08/cattitude-team-and-bertha-246x123.jpg" class="attachment-box-row1-col1 wp-post-image" alt="Cattitude" /></a>`						

<a class="box-image imgLiquidFill imgLiquid" href="http://vettimes.makemedia-test.com/news/success-for-cattitude-feline-focused-cpd-days/"><img width="246" height="123" src="http://vettimes.makemedia-test.com/wp-content/uploads/2015/08/cattitude-team-and-bertha-246x123.jpg" class="attachment-box-row1-col1 wp-post-image" alt="Cattitude" /></a>

**Comment by karacas** [comment]
Try use this in source:
'http://vettimes.makemedia-test.com/wp-content/uploads/2015/08/cattitude-team-and-bertha.jpg'
